#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v18
# autospec commit: f35655a
#
Name     : R-BiocGenerics
Version  : 0.50.0
Release  : 2
URL      : https://bioconductor.org/packages/release/bioc/src/contrib/BiocGenerics_0.50.0.tar.gz
Source0  : https://bioconductor.org/packages/release/bioc/src/contrib/BiocGenerics_0.50.0.tar.gz
Summary  : S4 generic functions used in Bioconductor
Group    : Development/Tools
License  : Artistic-2.0
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[<img src="https://www.bioconductor.org/images/logo/jpg/bioconductor_logo_rgb.jpg" width="200" align="right"/>](https://bioconductor.org/)

%prep
%setup -q -n BiocGenerics

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1724349418

%install
export SOURCE_DATE_EPOCH=1724349418
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/BiocGenerics/CITATION
/usr/lib64/R/library/BiocGenerics/DESCRIPTION
/usr/lib64/R/library/BiocGenerics/INDEX
/usr/lib64/R/library/BiocGenerics/Meta/Rd.rds
/usr/lib64/R/library/BiocGenerics/Meta/features.rds
/usr/lib64/R/library/BiocGenerics/Meta/hsearch.rds
/usr/lib64/R/library/BiocGenerics/Meta/links.rds
/usr/lib64/R/library/BiocGenerics/Meta/nsInfo.rds
/usr/lib64/R/library/BiocGenerics/Meta/package.rds
/usr/lib64/R/library/BiocGenerics/NAMESPACE
/usr/lib64/R/library/BiocGenerics/R/BiocGenerics
/usr/lib64/R/library/BiocGenerics/R/BiocGenerics.rdb
/usr/lib64/R/library/BiocGenerics/R/BiocGenerics.rdx
/usr/lib64/R/library/BiocGenerics/help/AnIndex
/usr/lib64/R/library/BiocGenerics/help/BiocGenerics.rdb
/usr/lib64/R/library/BiocGenerics/help/BiocGenerics.rdx
/usr/lib64/R/library/BiocGenerics/help/aliases.rds
/usr/lib64/R/library/BiocGenerics/help/paths.rds
/usr/lib64/R/library/BiocGenerics/html/00Index.html
/usr/lib64/R/library/BiocGenerics/html/R.css
/usr/lib64/R/library/BiocGenerics/tests/run_unitTests.R
/usr/lib64/R/library/BiocGenerics/unitTests/test_Extremes.R
/usr/lib64/R/library/BiocGenerics/unitTests/test_combine.R
/usr/lib64/R/library/BiocGenerics/unitTests/test_format.R
/usr/lib64/R/library/BiocGenerics/unitTests/test_mapply.R
/usr/lib64/R/library/BiocGenerics/unitTests/test_order.R
/usr/lib64/R/library/BiocGenerics/unitTests/test_paste.R
/usr/lib64/R/library/BiocGenerics/unitTests/test_updateObject.R
